# Generated by Django 6.0.1 on 2026-02-06 11:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='FullName', max_length=150)),
                ('email', models.EmailField(db_column='Email', max_length=200)),
                ('phone_number', models.CharField(db_column='Phone', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format.', regex='^\\+?\\d{9,15}$')])),
                ('flat_number', models.CharField(db_column='FlatNumber', max_length=50)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('joined', models.DateTimeField(auto_now_add=True, db_column='JoinedOn')),
            ],
            options={
                'db_table': 'residents',
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('address', models.TextField(db_column='Address', max_length=300)),
                ('city', models.CharField(db_column='City', max_length=100)),
                ('pincode', models.CharField(db_column='Pincode', max_length=6, validators=[django.core.validators.RegexValidator(message='Pin code must be exactly 6 digits.', regex='^[0-9]{6}$')])),
                ('created', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'societies',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.IntegerField(choices=[(1, 'Plumbing'), (2, 'Electrical'), (3, 'Security'), (4, 'Other')], db_column='Type', default=4, max_length=20)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('description', models.TextField(db_column='Description', max_length=2000)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Resolved'), (4, 'Closed'), (5, 'Cancelled')], db_column='Status', default=1, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('closed', models.DateTimeField(blank=True, db_column='ClosedAt', null=True)),
                ('resident', models.ForeignKey(db_column='ResidentId', on_delete=django.db.models.deletion.CASCADE, to='api.resident')),
            ],
            options={
                'db_table': 'service_requests',
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='society',
            field=models.ForeignKey(blank=True, db_column='SocietyId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.society'),
        ),
    ]
